LENGTH = "length"
NUM_WORDS = "num_words"
CONTAINS_QUESTION_MARK = "contains ?"
CONTAINS_EXCLAMATION_MARK = "contains !"
NUM_QUESTION_MARK = "num ?"
NUM_EXCLAMATION_MARK = "num !"
CONTAINS_HAPPY_EMOTICON = "CONTAINS_HAPPY_EMOTICON"
CONTAINS_SAD_EMOTICON = "CONTAINS_SAD_EMOTICON"
NUM_UPPER_CASE = "NUM_UPPER_CASE"
CONTAINS_COLON = "contains :"
CONTAINS_PLEASE = "CONTAINS_PLEASE"
NUM_POSITIVE_SENTIMENTS = "NUM_POSITIVE_SENTIMENTS"
NUM_NEGATIVE_SENTIMENTS = "NUM_NEGATIVE_SENTIMENTS"
NUM_FIRST_PERSON_PRON = "NUM_FIRST_PERSON_PRON"
NUM_SECOND_PERSON_PRON = "NUM_SECOND_PERSON_PRON"
NUM_THIRD_PERSON_PRON = "NUM_THIRD_PERSON_PRON"
NUM_SLANG = "NUM_SLANG"


FRACTION_UPPER_CASE = "fraction upper case"
NUM_URL = "num url"
EMBEDDING = "embedding"


ALL_FEATURES = [LENGTH, NUM_WORDS, CONTAINS_QUESTION_MARK, CONTAINS_EXCLAMATION_MARK, CONTAINS_HAPPY_EMOTICON, 
				CONTAINS_SAD_EMOTICON, FRACTION_UPPER_CASE, NUM_URL, EMBEDDING]

# ALL_FEATURES = [LENGTH, NUM_WORDS, CONTAINS_QUESTION_MARK, CONTAINS_EXCLAMATION_MARK, NUM_QUESTION_MARK, NUM_EXCLAMATION_MARK, 
# 				CONTAINS_HAPPY_EMOTICON, CONTAINS_SAD_EMOTICON, NUM_UPPER_CASE, CONTAINS_COLON, CONTAINS_PLEASE, 
# 				NUM_POSITIVE_SENTIMENTS, NUM_NEGATIVE_SENTIMENTS, NUM_FIRST_PERSON_PRON, NUM_SECOND_PERSON_PRON, NUM_THIRD_PERSON_PRON, NUM_SLANG]

				# FRACTION_UPPER_CASE, NUM_URL, EMBEDDING]

HAPPY_EMO = [":)",":-)","=)","(:",":D"]
SAD_EMO = [":(",":-(","=(","):",":'("]
